print("twinkle twinkle little star")
print("\t how i wonder what you are")
print("\t\t up above the world so high")
print("\t\t like a diamond in the sky")
print("twinkle twinkle little star ")
print("\t how i wonder what you are")
